version: "3.7"
services:
  memcached_server:
    image: memcached:1.6.10
    networks:
      nfv_network:
        ipv4_address: 192.0.2.11
        ipv6_address: 2001:DB8::2001:DB8:0:1
    container_name: nfv_memcache
    command:
      - '-m 10'
  gateway_nfv_scheduler:
    image: <nfv-scheduler-images>
    container_name: nfv_scheduler
    stdin_open: true
    tty: true
    networks:
      nfv_network:
        ipv4_address: 192.0.2.12
        ipv6_address: 2001:DB8::2001:DB8:0:2
    volumes:
      - <scheduler-logs-dir>:/statistics_collection/logs
      - <config-dir>:/config
  nfv_gateway:
    image: <nfv-gateway-images>
    container_name: nfv_gateway
    ports:
      - "8088:8000"
    networks:
      nfv_network:
        ipv4_address: 192.0.2.13
        ipv6_address: 2001:DB8::2001:DB8:0:3
    environment:
      - BAM_IP=<bam-ip>
      - LOCAL_USER_ID=<local-user-id>
    volumes:
      - <gw-logs-dir>:/logs
networks:
  nfv_network:
    name: nfv_network
    driver_opts:
        com.docker.network.enable_ipv6: "true"
    ipam:
      config:
        - subnet: 192.0.2.0/24
        - subnet: "2001:db8::/64"
